services:
  code:
    # build:
    #   context: ./dockerfile/
    #   args:
    #     - DOCKER_UID=${DOCKER_UID}
    #     - DOCKER_USER=${DOCKER_USER}
    #     - DOCKER_PASSWORD=${DOCKER_PASSWORD}
    image: codercom/code-server
    environment:
      PASSWORD: ${DOCKER_PASSWORD}
    volumes:
      # - ./project:/home/${DOCKER_USER}/
      - ./project:/root/project
    restart: always
  
  https-portal:
    image: steveltn/https-portal:latest
    container_name: https-portal
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: '${DOMAIN} -> http://code:8080'
      # STAGE: 'production' 
    depend_on: code